# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/gui_main_packaged.py'],  # 使用新的打包专用入口文件
    pathex=['.'],
    binaries=[],
    datas=[
        ('config.json', '.'),
        ('predefined_terms.csv', '.'),
        ('translation_data.csv', '.'),
        ('src/utils/translation', 'src/utils/translation'),
    ],
    hiddenimports=[
        'src',
        'src.gui',
        'src.gui.application_pyqt',
        'src.blast',
        'src.utils',
        'src.utils.translation',
        'src.utils.environment_checker',
        'Bio',
        'Bio.Blast',
        'Bio.SeqIO',
        'requests',
        'pandas',
        'lxml',
        'xml.etree.ElementTree',
        'csv',
        'pathlib',
        'os',
        'sys',
        'threading',
        'typing',
        'dataclasses',
        'logging',
        'datetime',
        'time',
        're',
        'urllib.parse',
        'urllib.request',
        'subprocess',
        'queue',
        'hashlib',
        'platform',
        'ctypes',
        'json',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'PyQt5',
        'PySide2',
        'tensorflow',
        'torch',
        'keras',
        'scipy.spatial.cKDTree',
        'sklearn',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='NCBI_BLAST_GUI',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # 改为False以隐藏控制台窗口
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='NCBI_BLAST_GUI',
)